import pandas as pd
import sqlite3 as sq

df_csv = pd.read_csv("Export2.csv", delimiter= ",")
with sq.connect("farms2.db") as con:
    cur = con.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS moreinfo (
            Website TEXT,
            street TEXT,
            County TEXT,
            OtherMedia TEXT,
            Facebook TEXT,
            Twitter TEXT,
            Youtube TEXT,
            Season1Date TEXT,
            Season1Time TEXT,
            Season2Date TEXT,
            Season2Time TEXT,
            Season3Date TEXT,
            Season3Time TEXT,
            Season4Date TEXT,
            Season4Time TEXT,
            x TEXT,
            y TEXT,
            Location TEXT,
            Credit TEXT,
            WIC TEXT,
            WICcash TEXT,
            SFMNP TEXT,
            SNAP TEXT,
            Organic TEXT,
            Bakedgoods TEXT,
            Cheese TEXT,
            Crafts TEXT,
            Flowers TEXT,
            Eggs TEXT,
            Seafood TEXT,
            Herbs TEXT,
            Vegetables TEXT,
            Honey TEXT,
            Jams TEXT,
            Maple TEXT,
            Meat TEXT,
            Nursery TEXT,
            Nuts TEXT,
            Plants TEXT,
            Poultry TEXT,
            Prepared TEXT,
            Soap TEXT,
            Trees TEXT,
            Wine TEXT,
            Coffee TEXT,
            Beans TEXT,
            Fruits TEXT,
            Grains TEXT,
            Juices TEXT,
            Mushrooms TEXT,
            PetFood TEXT,
            Tofu TEXT,
            WildHarvested TEXT )
            """)
    df_csv.to_sql(name='moreinfo', con=con)

